{{- if ne .Values.database.dialect "h2" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streampark.fullname" . }}-db
  labels:
    {{- include "streampark.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ include "streampark.jdbcUrl" . | quote }}
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
{{- end }}
